### ISSUE TITLE
openssl.cnf on openwrt

### ISSUE THREAD

**Issue by ssdnvv** [JW0914/Wikis#1]
Hi,

I downloaded the openssl.cnf and followed your description on https://wiki.openwrt.org/doc/howto/openvpn-streamlined-server-setup.
Unfortunatelly I run into the following error, when calling
`root@Eltern_Router:/etc/ssl# openssl req -x509 -new -sha512 -days 3650 -newkey rsa:4096 -keyout ca/OpenWrt-CA.key.pem -out ca/OpenWrt-CA.crt.pem -config ./openssl.cnf -extensions v3_ca_openwrt`

> 3069732036:error:0E065068:lib(14):func(101):reason(104):NA:0:line 68

I therefore opened https://forum.openwrt.org/viewtopic.php?id=71867.

Best,
ssdnvv

**Comment by JW0914** [comment]
@ssdnvv First, I apologize for the extremely late reply.  

I was about to post my reply when I noticed what I think may be the issue: I'm assuming you followed the prerequisite instructions in the bottom half of the config, issuing `echo 01 > crlnumber`?

- If so, I forgot to update that specific instruction with the edits done to `[ CA_default ]`, organizing CRL files into their own _crl_ directory, meaning _crlnumber_ was created in the root of the directory _openssl.cnf_ resides in, whereas `openssl` is looking for it at _crl/crlnumber_.  I've corrected this with [a8ba16a  ](https://github.com/JW0914/Wikis/commit/a8ba16a7cc30d45371e47feac89fe4fb50dcd798).
  - If this is not the issue, please post what distro you're utilizing so I can power up a VM and troubleshoot.

**Comment by JW0914** [comment]
As no further response has been posted on this issue, nor following my response in the aforementioned OpenWrt thread, I'm closing this _([a8ba16a](https://github.com/JW0914/Wikis/commit/a8ba16a7cc30d45371e47feac89fe4fb50dcd798) should have resolved the issue with lines 64 & 65)_.  

Please feel free to re-open if this did not resolve your issue.

**Comment by ssdnvv** [comment]
Sry, somehow missed that one here :( 
My distribution is a openwrt-fork (Turris Omnia).
I restarted from scratch (deleted folders and files, downloaded your actual openssl.cnf and followed again your instructions on https://wiki.openwrt.org/doc/howto/openvpn-streamlined-server-setup).
There are some remnants of former versions that need to be changed:
`extensions v3_ca_main` needs to be changed to `extensions v3_ca`
`v3_openvpn_server` needs to be changed to `v3_vpn_server2`
`openssl x509 -req -sha512 -days 3650 -in ca/csr/vpn-client1.csr -CA ca/OpenWrt-CA.crt.pem -CAkey ca/OpenWrt-CA.key -CAserial ./serial -out openvpn/clients/vpn-client1-<username>-<hostname>.crt.pem -extfile ./openssl.cnf -extensions v3_vpn2_user1` --> here `OpenWrt-CA.key` needs to be changed to `OpenWrt-CA.key.pem`

The path to the index-file within openssl.cnf seems to not be working:
```
root@OpenWrt:/etc/ssl# openssl ca -gencrl -keyfile ca/OpenWrt-CA.key.pem -cert ca/OpenWrt-CA.crt.pem -out crl/OpenWrt-CA.crl.pem -config ./openssl.cnf
Using configuration from ./openssl.cnf
Enter pass phrase for ca/openVPN-CA.key.pem:
.\index: No such file or directory
unable to open '.\index'
3069948592:error:02001002:lib(2):func(1):reason(2):NA:0:fopen('.\index','r')
3069948592:error:20074002:lib(32):func(116):reason(2):NA:0:
```
I double-checked that the index-file is existent and empty.
In order to proceed I changed the paths in the openssl.cnf from `database                        = $dir\\index` to `database                        = ./index`

I haven't tested the OpenVPN-connection yet but assume that it will work.
Thanks for your work!

**Comment by JW0914** [comment]
Right... you're misunderstanding what a preconfigured openssl.cnf is, as it, in and of itself, isn't the issue.

- The section names are arbitrary and can be customized to whatever one wishes and are not "intended" to be utilized as is
   - While they can be, one is supposed to customize them to their own environment.
- The issues you're reporting aren't issues, but changes one is supposed to do on their own to customize the openssl.cnf, especially the arbitrary names, to _their_ environment.

Your issues are also a result of not reading Lines 3 and 12 - 18... please see Lines 12 - 18 to understand why `database = $dir\\index` wasn't working for you.

**Comment by ssdnvv** [comment]
Yes, you're right - I did not follow your *.cnf-file instructions but your instructions on https://wiki.openwrt.org/doc/howto/openvpn-streamlined-server-setup (as I stated above). There you do have detailed instructions for openwrt in combination with that file. I followed that instructions and it won't work with that instructions. I just wanted to help in order to make those instructions work.
If you made this file for multiple purposes that's fine (and - again - thanks for your work), but for the purpose of making it work with openwrt you need to change some of the instructions on https://wiki.openwrt.org/doc/howto/openvpn-streamlined-server-setup and some of the terms inside the file.
Anyway - take it or leave it. I just wanted to help making it work for someone completely new to openwrt. You are right - someone a little bit more familiar with that stuff can fix those little things on his/her own.

**Comment by JW0914** [comment]
You may not realize, but you can edit an OpenWrt wiki yourself by creating a Wiki account.  If it's something as simple as needing to have the V3 profile names updated to bring it inline with any edits I perform to the openssl config, it would be far less convoluted for the user noticing the need for an update to simply perform the update themselves.

- It would have taken someone less than 3min to update the handful of things I've updated, instead of 38 days from the genesis of this issue until today.  

[Diff of edits performed on the Wiki](https://wiki.openwrt.org/doc/howto/openvpn-streamlined-server-setup?rev=1505485549&do=diff)

**Comment by JW0914** [comment]
@ssdnvv After re-reading your replies, it's apparent I was missing the larger point you were trying to make.  Thank you for the feedback =]

**Comment by ssdnvv** [comment]
:)
You're welcome.
