### ISSUE TITLE
Hi can you put a WRT3200ACM mtd3 dump here...

### ISSUE THREAD

**Issue by hyyz17200** [JW0914/Wikis#2]
Its devinfo partition. I don't know how i just get it lost and my OEM firmware cannot bootup
( in facts it can, but cannot log into web UI)
I need a sample devinfo to replace my info to it.

Thanks!

**Comment by hyyz17200** [comment]
Yes, mtd3 contains unique data, but actually I want a sample, and I will use my info from router lable to replace it. 

My type is the newest one, yeah the Winbond one.

So I just find a mtd3 info sample of wrt1900acs here: [https://community.linksys.com/t5/Wireless-Routers/How-to-restore-the-data-device-ID/td-p/958652/page/2](url) [https://github.com/Chadster766/McWRT/wiki/Rebuild-the-devinfo-MTD-partition](url)

I just replaced my info with this sample, some entrys do not appear in my lable, so I guess by myself.

Also I find a problem to write into mtd3, coz I was in a situation that I cannot boot into Linksys firmware ( my part1 is broken that time, and part2 is the linksys)

So I use TTLtoUSB hardware and Putty to login Uboot. And use another command to write.

devinfo erase
devinfo set cert_region=US
devinfo set default_passphrase=fw7kx5rrxm
devinfo set default_ssid=Linksys02494
devinfo set deviceType=urn:home-linksys-com:device:Router:1
devinfo set devinfo_version=20131025.1
devinfo set hw_mac_addr=60:38:E0:CB:A9:08
devinfo set hw_revision=1
devinfo set hw_version=48SAM203.0GA
devinfo set manufacturer=Linksys, LLC
devinfo set manufacturerURL=http://www.linksys.com
devinfo set manufacturer_date=2017/03/17
devinfo set mfg_data_version=1
devinfo set modelDescription=Simultaneous Dual-Band Wireless-AC Gigabit Router
devinfo set modelNumber=WRT3200ACM
devinfo set serial_number=1981160C702494
devinfo set sw_version=v1.0.0
devinfo set tc_passphrase=TCfw7kx5rrxm
devinfo set tc_ssid=TCLinksys02494
devinfo set uuid_key=89060742-18bd-4c42-9d37-315d7b4231f9
devinfo set wps_device_pin=99261092
devinfo commit

Then after rebooting, Linksys firmware works! And I can flash openwrt to part1...

Another thing needs to be mention is: I was using CH341A module to connect TTL to USB, but it cannot boot with cables connected, the router hangs. The solution is remove the cables, and open the router power switch, insert the cables immediately and press space bar in Putty.

I write down these just want to show the solution to anyone may face this issue too.
Hope it will work!

And thank you!

**Comment by JW0914** [comment]
No problem at all =]

If eSATA LED lights immediately after reboot with no serial output, add a 4.7KΩ resistor between Gnd & Rx on adapter
* 4.7KΩ 4 Band: 
   * yel | pur | red | gold (±5%) <br><br>
* 4.7KΩ 5 Band: 
   * yel | pur | blk | brn | brn (±1%)<br><br>

This can also be found in the [WRT AC Series ToH](https://openwrt.org/toh/linksys/wrt_ac_series) wiki:
* **Troubleshooting** -> **Serial Interfaces** -> **[USB-to-UART](https://openwrt.org/toh/linksys/wrt_ac_series#usb-to-uart)**
